### ISSUE TITLE
Reporting not working with https://petstore.swagger.io

### ISSUE THREAD

**Issue by drozdovkostya** [reqover/docs#11]
Steps to reproduce:

Deploy application to Heroku
Leave default configuration
   "API_SERVICE_URL": "https://petstore.swagger.io",
    "SWAGGER_SPEC_URL": "https://petstore.swagger.io/v2/swagger.json"
Make GET request to https://petstore.swagger.io/v2/store/inventory, status 200
Refresh Heroku app page.

Actual result:
Covered 0

Expected result:
Covered 1

See attachments:

<img width="1406" alt="Screenshot 2021-08-19 at 18 41 50" src="https://user-images.githubusercontent.com/36082700/130099487-fa4859a7-1a14-40d4-9946-10c0e174defc.png">
<img width="1400" alt="Screenshot 2021-08-19 at 18 42 06" src="https://user-images.githubusercontent.com/36082700/130099510-9616fb97-c622-459e-a15a-a672fba90bef.png">
<img width="1420" alt="Screenshot 2021-08-19 at 18 42 51" src="https://user-images.githubusercontent.com/36082700/130099529-f2b91ad1-fe21-40b0-87ff-08384dd798ef.png">

**Comment by rsriz** [comment]
@drozdovkostya I believe you should try **proxy api path** + resource

**Comment by artemkapset** [comment]
The same issue is for me. I run Reqover locally, not on Heroku...

**Comment by artemkapset** [comment]
> The same issue is for me. I run Reqover locally, not on Heroku...

the problem is solved. if 'reqover' is running locally, use the url: http://localhost:3000/reqover/swagger/v2/store/inventory
