### ISSUE TITLE
Add report.html download link

### ISSUE THREAD

**Issue by savvagen** [reqover/docs#2]

**Comment by SergeyPirogov** [comment]
@savvagen Could you please explain this feature?

**Comment by savvagen** [comment]
> @savvagen Could you please explain this feature?

The main question is, - how to run the same TestRun on live recover service over and over again? Are we able to track test coverage results all the time without killing and rerunning the service?

**Comment by savvagen** [comment]
> > @savvagen Could you please explain this feature?
> 
> The main question is, - how to run the same TestRun on live recover service over and over again? Are we able to track test coverage results all the time without killing and rerunning the service?

serer keeps all results
