### ISSUE TITLE
Error occured while trying to proxy to: localhost:3000

### ISSUE THREAD

**Issue by Bigjoehackl** [reqover/docs#7]

**Comment by SergeyPirogov** [comment]
@Bigjoehackl please provide more details. What you did and what is error

**Comment by Bigjoehackl** [comment]
Step 1. docker run -p 3000:3000 reqover/reqover:latest = successful running
Step 2. Open http://localhost:3000/ = Error occured while trying to proxy to: localhost:3000
But http://localhost:3000/reqover/ opens

**Comment by Morena51** [comment]
I had the same issue with step 2 in README.md:
`curl --location --request GET 'http://localhost:3000/v2/pet/9222968140497128105'`

Logs
```
 Router target http://localhost:8080 {"timestamp":"2021-05-29 20:52:59"}
[HPM] Error occurred while trying to proxy request  from localhost:3000 to http://localhost:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
::ffff:172.17.0.1 - - [29/May/2021:20:52:59 +0000] "GET / HTTP/1.1" 504 - "-" "curl/7.64.1"
```

**Comment by SergeyPirogov** [comment]
Docker ca not acess localhost. To be able to acess localhost you have to run reqover container using 
- - net=host to

**Comment by serhiiyasenev** [comment]
it seems that the app doesn't work with `--net="host"`, does it?
![image](https://user-images.githubusercontent.com/29712777/122396108-5728fe80-cf80-11eb-8e9c-5c05293ab7e0.png)
